-- Drop table
DROP TABLE files;
DROP TABLE word_counts;

-- Create a table to store results
CREATE TABLE files (line STRING);

-- Load data into the database using a file on your local system (NOT HDFS)
LOAD DATA LOCAL INPATH '/file01.txt' INTO TABLE files;

-- Create a new table using data from the files table
CREATE TABLE word_counts AS
SELECT word, COUNT(word) as wordCount FROM
(SELECT EXPLODE(SPLIT(line,' ')) as word FROM files) w
GROUP BY word
ORDER BY wordCount DESC;